<a href="https://colab.research.google.com/github/AnuMaryJohn/Python-Projects/blob/main/Assignment_4_Mathematics_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Mathematics for Data Science**

## **Question 1**

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("/content/winequality-red.csv",sep=';')
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [3]:
df.fillna(df.mean(),inplace=True)

In [4]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

## **Question 2**

In [5]:
Citric_acid=df['citric acid'].values
print('Citric_acid vector is:',Citric_acid)

Citric_acid vector is: [0.   0.   0.04 ... 0.13 0.12 0.47]

In [6]:
Alcohol=df['alcohol'].values
print('Alcohol vector is:',Alcohol)

Alcohol vector is: [ 9.4  9.8  9.8 ... 11.  10.2 11. ]

## **Question 3**

In [7]:
x=df[['density','alcohol']].values
cov_matrix=np.cov(x.T)
print(cov_matrix)

[[ 3.56202945e-06 -9.97951790e-04]
 [-9.97951790e-04  1.13564740e+00]]

## **Question 4**

In [8]:
eigenvalues,eigenvectors=np.linalg.eig(cov_matrix)
print('eigen values are:',eigenvalues)
print('eigen vectors are:',eigenvectors)

eigen values are: [2.68507580e-06 1.13564827e+00]
eigen vectors are: [[-9.99999614e-01  8.78753184e-04]
 [-8.78753184e-04 -9.99999614e-01]]

## **Question 5**

In [9]:
print("most commonwine quality is:")
df['quality'].mode()

most commonwine quality is:

0    5
Name: quality, dtype: int64

In [10]:
df1=df['quality'].value_counts().reset_index(name="count")
print("Wine quality distribution:\n", df1)

Wine quality distribution:
    quality  count
0        5    681
1        6    638
2        7    199
3        4     53
4        8     18
5        3     10

### OR

In [11]:
most_common = df1[df1['count']==df1['count'].max()]
print("Most common wine quality is:\n",most_common)

Most common wine quality is:
    quality  count
0        5    681